arb-dir: lib/l10n/arbs
template-arb-file: app_en.arb
output-dir: lib/l10n/gen
output-localization-file: app_localizations.dart
synthetic-package: false
nullable-getter: false
untranslated-messages-file: l10n_untranslated_messages.json
