include: package:flutterando_analysis/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics-exclude:
    - test/**
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 3
    maximum-nesting-level: 5
    lines-of-code: 30
  rules:
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-object-declaration
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-expanded-as-spacer
    - avoid-wrapping-in-padding
    - prefer-correct-edge-insets-constructor
    - prefer-single-widget-per-file
    - prefer-extracting-callbacks
    - avoid-dynamic
    - prefer-async-await
    - prefer-commenting-analyzer-ignores
    - avoid-nested-conditional-expressions
    - avoid-unnecessary-conditionals
    - prefer-enums-by-name
    - prefer-moving-to-variable
    - prefer-static-class
    - member-ordering:
        order:
          - constructors
          - public-fields
          - private-fields
          - close-method
          - dispose-method
        widgets-order:
          - constructor
          - init-state-method
          - did-change-dependencies-method
          - did-update-widget-method
          - dispose-method
          - build-method

linter:
  rules:
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    use_super_parameters: true
    only_throw_errors: true
    directives_ordering: true
    prefer_relative_imports: true
    avoid_print: true
