include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 3
    source-lines-of-code: 30
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return # Opcional
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma # Opcional, mais pra não
    - no-equal-then-else
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-dynamic
    - prefer-async-await
    - prefer-commenting-analyzer-ignores

linter:
  rules:
    - require_trailing_commas







