name: app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: 3.3.10

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  core_module:
    path: ../core_module
  auth_module:
    path: ../auth_module
  app_dependencies:
    path: ../app_dependencies
  design_system:
    path: ../design_system

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
